const base = process.env.STARMEGAMAN_URL || 'http://127.0.0.1:5187'
import { chromium } from '../paramotor/node_modules/@playwright/test/index.mjs'
import assert from 'node:assert/strict'
import { mkdir } from 'node:fs/promises'
await mkdir('test-results/starmegaman', { recursive: true })
const browser = await chromium.launch({ channel: 'msedge', headless: true })
try {
const errors = []
const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, deviceScaleFactor: 1 })
page.on('pageerror', error => errors.push(error.message))
await page.goto(base + '/starmegaman')
await page.getByRole('button', { name: 'Ta nattskiftet' }).waitFor()
await page.waitForTimeout(900)
await page.screenshot({ path: 'test-results/starmegaman/desktop-title.png', fullPage: true })
assert.equal(await page.locator('h1').textContent(), 'StarMegaMan')
await page.getByRole('button', { name: 'Ta nattskiftet' }).click()
await page.keyboard.down('ArrowRight'); await page.keyboard.down('KeyX'); await page.waitForTimeout(2600)
await page.keyboard.down('Space'); await page.waitForTimeout(160); await page.keyboard.up('Space'); await page.waitForTimeout(80); await page.keyboard.down('Space'); await page.waitForTimeout(230); await page.keyboard.up('Space')
await page.keyboard.up('ArrowRight'); await page.keyboard.up('KeyX')
await page.screenshot({ path: 'test-results/starmegaman/desktop-playing.png' })
await page.keyboard.press('KeyP'); await page.getByRole('heading', { name: 'En liten paus.' }).waitFor()
await page.getByRole('button', { name: 'Fortsätt spela', exact: true }).last().click()
await page.getByRole('button', { name: 'Stäng av ljud' }).click(); await page.getByRole('button', { name: 'Slå på ljud' }).waitFor()
await page.getByRole('button', { name: 'Pausa', exact: true }).click()
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)

const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true })
const phone = await mobile.newPage(); phone.on('pageerror', error => errors.push(error.message))
await phone.goto(base + '/starmegaman'); await phone.getByRole('button', { name: 'Ta nattskiftet' }).waitFor(); await phone.waitForTimeout(900)
await phone.screenshot({ path: 'test-results/starmegaman/mobile-title.png', fullPage: true })
assert.equal(await phone.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
await phone.getByRole('button', { name: 'Ta nattskiftet' }).click()
await phone.locator('.smm-game').scrollIntoViewIfNeeded()
const cdp = await mobile.newCDPSession(phone)
const boxRight = await phone.getByRole('button', { name: 'Gå höger', exact: true }).boundingBox()
const boxFire = await phone.getByRole('button', { name: 'Skjut stjärnljus', exact: true }).boundingBox()
const point = (box, id) => ({ x: box.x + box.width / 2, y: box.y + box.height / 2, id })
await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [point(boxRight, 1), point(boxFire, 2)] })
await phone.waitForTimeout(2200)
await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
await phone.screenshot({ path: 'test-results/starmegaman/mobile-playing.png' })
assert.ok(Number(await phone.locator('.smm-score span').textContent()) > 0, 'Multitouch movement collects stars')
await phone.getByRole('button', { name: 'Pausa', exact: true }).click(); await phone.getByRole('heading', { name: 'En liten paus.' }).waitFor()
await phone.getByRole('button', { name: 'Öppna meny' }).click(); await phone.locator('#mobile-menu').getByRole('link', { name: /StarMegaMan/ }).waitFor()
await phone.getByRole('button', { name: 'Stäng meny' }).click()
await phone.getByRole('button', { name: 'Fortsätt spela', exact: true }).last().click()
await phone.getByRole('button', { name: 'Helskärm', exact: true }).click(); await phone.waitForTimeout(400)
await phone.screenshot({ path: 'test-results/starmegaman/mobile-fullscreen.png' })
if (await phone.getByRole('button', { name: 'Lämna helskärm' }).count()) await phone.getByRole('button', { name: 'Lämna helskärm' }).click()
await phone.goto(base + '/'); await phone.getByRole('link', { name: /StarMegaMan · Pixeläventyr/ }).waitFor()
assert.deepEqual(errors, [])
console.log('PASS: desktop start, keyboard, double jump, shooting, pause/resume, audio; 390px layout, multitouch, fullscreen, navigation, homepage; no page errors.')
} finally { await browser.close() }
