import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';

await mkdir('test-results', { recursive: true });
const browser = await chromium.launch({ channel: 'chrome', headless: true, args: ['--enable-webgl', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
try {
  await page.goto(process.env.AER_URL || 'http://127.0.0.1:5173/');
  await page.waitForFunction(() => window.__AER__?.ready, { timeout: 30000 });
  await page.waitForTimeout(1200);
  assert.deepEqual(errors, [], 'Initial scene shaders compile');
  await page.screenshot({ path: 'test-results/welcome.png' });
  await page.getByRole('button', { name: 'Enter flight' }).click();
  await page.waitForTimeout(1200);
  const initial = await page.evaluate(() => window.__AER__.snapshot());
  assert.equal(initial.running, true);
  await page.keyboard.down('Space'); await page.waitForTimeout(2200);
  const powered = await page.evaluate(() => window.__AER__.snapshot());
  assert(powered.throttle > .8, 'Space must increase engine power');
  await page.keyboard.down('ArrowRight'); await page.keyboard.down('f'); await page.waitForTimeout(1500);
  const turning = await page.evaluate(() => window.__AER__.snapshot());
  assert(turning.rightBrake > .7 && turning.weight > .8 && turning.bank > .1, 'Right brake and F must bank right');
  await page.screenshot({ path: 'test-results/flight.png' });
  await page.keyboard.down('ArrowUp'); await page.waitForTimeout(1300);
  const released = await page.evaluate(() => window.__AER__.snapshot());
  assert(released.rightBrake < .2, 'Hands up must override a held brake');
  for (const key of ['ArrowRight', 'ArrowUp', 'f', 'Space']) await page.keyboard.up(key);
  await page.keyboard.press('p');
  await page.getByRole('heading', { name: 'Take a breath.' }).waitFor();
  const paused = await page.evaluate(() => window.__AER__.snapshot());
  await page.waitForTimeout(400);
  assert.equal((await page.evaluate(() => window.__AER__.snapshot())).time, paused.time, 'Pause must stop physics');
  await page.getByRole('button', { name: 'Continue flight' }).click();
  await page.keyboard.press('h');
  await page.getByRole('heading', { name: 'A feel for flight.' }).waitFor();
  await page.screenshot({ path: 'test-results/guide.png' });
  await page.keyboard.press('Escape');
  assert.equal(await page.evaluate(() => window.__AER__.snapshot().running), true);
  await page.getByRole('button', { name: 'SETTINGS' }).click();
  await page.selectOption('#weather-select', 'calm');
  await page.selectOption('#quality-select', 'balanced');
  await page.getByRole('button', { name: 'Apply & return' }).click();
  assert.equal(await page.evaluate(() => window.__AER__.snapshot().weather), 'calm');
  await page.keyboard.press('r');
  assert((await page.evaluate(() => window.__AER__.snapshot())).time < 1, 'Restart resets flight');
  await page.setViewportSize({ width: 800, height: 600 });
  await page.waitForTimeout(300);
  await page.screenshot({ path: 'test-results/compact.png' });
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.getByRole('link', { name: 'AER home' }).click();
  await page.getByRole('button', { name: 'Start on the field' }).click();
  assert.equal((await page.evaluate(() => window.__AER__.snapshot())).status, 'ground');
  await page.keyboard.down('Space');
  await page.waitForFunction(() => window.__AER__.snapshot().agl > 8, { timeout: 25000 });
  const takeoff = await page.evaluate(() => window.__AER__.snapshot());
  assert.equal(takeoff.status, 'flying');
  await page.screenshot({ path: 'test-results/takeoff.png' });
  await page.keyboard.up('Space');
  const frameTimes = await page.evaluate(async () => {
    const times = []; let previous = performance.now();
    await new Promise(resolve => { const tick = now => { times.push(now - previous); previous = now; times.length < 90 ? requestAnimationFrame(tick) : resolve(); }; requestAnimationFrame(tick); });
    return times.slice(1);
  });
  const meanFrameMs = frameTimes.reduce((a, b) => a + b, 0) / frameTimes.length;
  assert.deepEqual(errors, [], 'No runtime or shader errors');
  console.log(JSON.stringify({ browser: 'Chrome', renderer: { drawCalls: initial.drawCalls, triangles: initial.triangles }, checks: ['launch', 'throttle', 'brake', 'weight shift', 'release override', 'pause', 'resume', 'help', 'settings', 'restart', 'compact viewport', 'ground takeoff'], takeoffAGL: takeoff.agl, meanFrameMs, errors, result: 'PASS' }, null, 2));
} finally { await browser.close(); }
