import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';

await mkdir('test-results', { recursive: true });
const browser = await chromium.launch({ channel: 'chrome', headless: true, args: ['--enable-webgl', '--ignore-gpu-blocklist'] });
const context = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true });
const page = await context.newPage(), errors = [];
page.on('pageerror', e => errors.push(e.message));
page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
const snapshot = () => page.evaluate(() => window.__AER__.snapshot());
const size = async (selector, value) => { await page.locator(selector).fill(String(value)); await page.locator(selector).dispatchEvent('input'); };
try {
  await page.goto(process.env.AER_URL || 'http://127.0.0.1:5173/');
  await page.waitForFunction(() => window.__AER__?.ready);
  assert(await page.locator('body').evaluate(el => el.classList.contains('touch-device')));
  await size('#welcome-wing', 32);
  assert.equal((await snapshot()).area, 32);
  await page.screenshot({ path: 'test-results/mobile-welcome.png' });
  await page.reload(); await page.waitForFunction(() => window.__AER__?.ready);
  assert.equal((await snapshot()).area, 32, 'wing size survives reload');
  await page.getByRole('button', { name: 'Enter flight' }).tap();
  assert(await page.locator('#touch-controls').isVisible());
  assert(!(await page.locator('.map-panel').isVisible()));
  await page.screenshot({ path: 'test-results/mobile-flight.png' });
  const cdp = await context.newCDPSession(page);
  const center = async (selector, id) => { const r = await page.locator(selector).boundingBox(); return { x: r.x + r.width / 2, y: r.y + r.height / 2, id }; };
  const left = await center('[data-pad=left]', 1), right = await center('[data-pad=right]', 2), thrust = await center('#touch-throttle', 3);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [left, right, thrust] });
  await page.waitForFunction(() => { const s = window.__AER__.snapshot(); return s.leftBrake > 1.15 && s.rightBrake > 1.15 && s.throttle > .8; });
  const held = await snapshot();
  assert(held.leftBrake > 1 && held.rightBrake > 1, 'three simultaneous touches and uncapped travel');
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [left] });
  await page.waitForFunction(() => { const s = window.__AER__.snapshot(); return s.leftBrake < .1 && s.rightBrake > 1.5 && s.throttle > .8; });
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchCancel', touchPoints: [] });
  await page.waitForFunction(() => { const s = window.__AER__.snapshot(); return s.rightBrake < .1 && s.throttle < .1; });
  await page.getByRole('button', { name: 'Pause flight' }).tap();
  assert.equal((await snapshot()).running, false);
  await page.getByRole('button', { name: 'New flight', exact: true }).tap();
  await page.locator('#touch-mode').tap();
  const riser = await center('[data-pad=left]', 1);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [riser] });
  await page.waitForFunction(() => window.__AER__.snapshot().leftCollapse > .7);
  await page.screenshot({ path: 'test-results/mobile-collapse.png' });
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  await page.getByRole('button', { name: 'SETTINGS' }).tap();
  await size('#settings-wing', 14);
  await page.getByRole('button', { name: 'Apply & return' }).tap();
  const resized = await snapshot(); assert.equal(resized.area, 14); assert(resized.time < 1 && resized.leftCollapse < .01);
  await page.setViewportSize({ width: 844, height: 390 });
  await page.waitForTimeout(350);
  await page.screenshot({ path: 'test-results/mobile-landscape.png' });
  await page.locator('#touch-mode').tap();
  const lean = await center('[data-pad=right]', 2);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [lean] });
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ ...lean, x: lean.x + 50 }] });
  await page.waitForFunction(() => window.__AER__.snapshot().weight > .8);
  assert((await snapshot()).rightBrake < .2, 'sideways touch lean without deep brake');
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchCancel', touchPoints: [] });
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({ result: 'PASS', checks: ['mobile detection', 'portrait and landscape', 'wing size persistence', 'three-finger brakes and throttle', 'independent release', 'touch cancellation', 'pause', 'riser collapse', 'size change restarts flight', 'touch weight steering'], errors }, null, 2));
} catch (error) { console.error('Failure snapshot', await snapshot()); await page.screenshot({path:'test-results/mobile-failure.png'}); throw error; } finally { await browser.close(); }
